fixtures:
  repositories:
    archive: "git@github.com:voxpupuli/puppet-archive.git"
    stdlib: "git@github.com:puppetlabs/puppetlabs-stdlib.git"
    java: "git@github.com:puppetlabs/puppetlabs-java.git"
    wget: "git@github.com:rehanone/puppet-wget.git"
