fixtures:
  symlinks:
    minecraft: "#{source_dir}"
  repositories:
    archive: "git://github.com/voxpupuli/puppet-archive.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    java: "git://github.com/puppetlabs/puppetlabs-java.git"
    wget: "git://github.com/maestrodev/puppet-wget.git"
